"""empty message

Revision ID: 232d28c2a231
Revises: c936f52a13a2
Create Date: 2019-12-30 22:23:26.328862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '232d28c2a231'
down_revision = 'c936f52a13a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('strength', sa.Float(precision=2), nullable=False),
    sa.Column('visibility', sa.Boolean(), nullable=False),
    sa.Column('input_file', sa.String(length=250), nullable=False),
    sa.Column('output_file', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('testcases')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testcases',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('strength', mysql.FLOAT(), nullable=False),
    sa.Column('visibility', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('input_file', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('output_file', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('challenge_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name='testcases_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('test_cases')
    # ### end Alembic commands ###
