"""empty message

Revision ID: 340a574ac7ed
Revises: 4ef278bcb68e
Create Date: 2019-12-30 21:00:38.470436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '340a574ac7ed'
down_revision = '4ef278bcb68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges_tags', 'challenge_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('challenges_tags', 'tag_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges_tags', 'tag_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('challenges_tags', 'challenge_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
