"""empty message

Revision ID: 5788036987a4
Revises: 66b271bb186e
Create Date: 2019-12-31 09:10:56.195177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5788036987a4'
down_revision = '66b271bb186e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_format', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('output_format', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('problem_statement', sa.Text(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('public_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['public_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('public_id')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('problem_statement')
        batch_op.drop_column('output_format')
        batch_op.drop_column('input_format')

    # ### end Alembic commands ###
