"""empty message

Revision ID: bf9853b5d912
Revises: 9f158cd053f1
Create Date: 2019-12-30 20:19:29.175561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf9853b5d912'
down_revision = '9f158cd053f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('sample_input', sa.Text(), nullable=False),
    sa.Column('sample_output', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_name', sa.String(length=80), nullable=False),
    sa.Column('start', sa.DateTime(timezone=120), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('show_leaderboard', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start')
    )
    op.create_table('challenge_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_name', sa.String(length=20), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('memory_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', mysql.VARCHAR(length=250), nullable=False))
    op.drop_table('challenge_settings')
    op.drop_table('contests')
    op.drop_table('challenges')
    # ### end Alembic commands ###
