"""empty message

Revision ID: c936f52a13a2
Revises: 47b460d36c20
Create Date: 2019-12-30 22:22:49.001928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c936f52a13a2'
down_revision = '47b460d36c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testcases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('strength', sa.Float(precision=2), nullable=False),
    sa.Column('visibility', sa.Boolean(), nullable=False),
    sa.Column('input_file', sa.String(length=250), nullable=False),
    sa.Column('output_file', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testcases')
    # ### end Alembic commands ###
